- src/api/nodeRpcCall.js
This was merged into a wrong branch by mistake on #19
> Fetch LLM balance from assets pallet

- src/api/eth.js
- src/api/explorer.js
- src/api/nodeRpcCall.js
- src/assets/abis/Bridge.json
- src/components/Wallet/Bridge/Connect/index.js
- src/components/Wallet/Bridge/EthereumToSubstrate/NewTransfer.js
- src/components/Wallet/Bridge/EthereumToSubstrate/Transfer.js
- src/components/Wallet/Bridge/EthereumToSubstrate/Transfers.js
- src/components/Wallet/Bridge/SubstrateToEthereum/Instruction.js
- src/components/Wallet/Bridge/SubstrateToEthereum/Transfers.js
- src/components/Wallet/Bridge/index.js
- src/hooks/useEthBridges.js
- src/hooks/useSubstrateBridgeTransfer.js
- src/index.js
- src/redux/actions/bridge.js
- src/redux/reducers/bridge.js
- src/redux/sagas/bridge.js
- src/redux/sagas/index.js
- src/redux/selectors/bridge.js
- src/redux/store/localStorage.js
- src/utils/bridge.js
Merge https://github.com/liberland/liberland_frontend/pull/85 first.
> LB-33 - Bridge transfer metadata fetched from chain explorer / eth json-rpc

- src/components/Profile/index.js
> BLOCKCHAIN-86 - Fix balances on profile page

- src/api/nodeRpcCall.js
- src/components/AuthComponents/SignIn/index.js
- src/components/InputComponents/Checkbox.js
- src/components/InputComponents/SelectInput.js
- src/components/InputComponents/styles.module.scss
- src/components/Modals/OnchainIdentityModal.js
- src/components/Profile/index.js
- src/utils/identityParser.js
> Blockchain-83 - E-resident checkbox in users identity form

- src/App.js
- src/api/nodeRpcCall.js
- src/components/Loader/index.js
- src/components/Modals/ChoseStakeModal.js
- src/components/Validators/Overview/index.js
- src/components/Validators/ValidatorsHeader/index.js
- src/components/Wallet/WalletAddressesLine/index.js
- src/redux/actions/index.js
- src/redux/actions/validator.js
- src/redux/reducers/index.js
- src/redux/reducers/validator.js
- src/redux/sagas/index.js
- src/redux/sagas/validator.js
- src/redux/selectors/index.js
- src/redux/selectors/validator.js
> BLOCKCHAIN-85 - payout staking rewards button

- src/components/Congress/Motions/index.js
- src/components/Congress/Overview/index.js
- src/components/Congress/ProposeRepealLegislationButton/index.js
- src/components/Congress/RepealLegislationButton/index.js
- src/components/Congress/Treasury/index.js
- src/components/Congress/Treasury/styles.module.scss
- src/components/Congress/styles.module.scss
- src/components/Legislation/LegislationView/index.js
- src/components/Legislation/LegislationView/styles.module.scss
- src/components/Modals/TreasurySpendingMotionModal.js
- src/components/Offices/Finances/index.js
> BLOCKCHAIN-153 FE - make congress FE pretty

- src/api/nodeRpcCall.js
Substrate PR: https://github.com/liberland/liberland_substrate/pull/326
> BLOCKCHAIN-190 - different tallying rules for fast tracked congress referenda

- src/api/nodeRpcCall.js
- src/components/Congress/Overview/index.js
- src/components/Voting/Referendum/Items/ProposalItem/index.js
- src/components/Voting/Referendum/Items/ProposalItem/styles.module.scss
- src/components/Voting/Referendum/Items/ReferendumItem/index.js
- src/components/Voting/Referendum/Items/ReferendumItem/styles.module.scss
- src/redux/actions/congress.js
- src/redux/reducers/congress.js
- src/redux/sagas/congress.js
- src/redux/sagas/index.js
Substrate PR: https://github.com/liberland/liberland_substrate/pull/329
> BLOCKCHAIN-164 - Congress & Senate should be pallet-democracy BlacklistOrigin

- package.json
- src/api/nodeRpcCall.js
- src/components/Loader/index.js
- src/components/Modals/DeleteCompanyModal.js
- src/components/Offices/CompanyRegistry/index.js
- src/components/Registries/RegistriesCompanies/CompanyCRUD/index.js
- src/components/Registries/RegistriesCompanies/index.js
- src/redux/reducers/registries.js
- src/redux/sagas/registries.js
- src/redux/selectors/registries.js
- src/utils/defaultData.js
- src/utils/registryFormBuilder.js
- yarn.lock
Using sample data:
Original JSON encoding: 3279 bytes
JSON encoding + deflate compressed: 827 bytes
SCALE encoded: 1073 bytes
This PR - SCALE encoded + deflate compressed: 459 bytes
So for sample data we've reduced data size by 86%.
> BLOCKCHAIN-240 + BLOCKCHAIN-246 + BLOCKCHAIN-247 - optimize company data format + small UX improvements + bugfixes

- src/components/Modals/OnchainIdentityModal.js
The fix is just the `isOlderThan15` change on line 129. Everything else is making linter happy.
> BLOCKCHAIN-305 - fix crash on updating identity

- src/components/Modals/VoteOnReferendumModal.js
- src/components/Voting/Referendum/Items/ProposalItem/index.js
- src/components/Voting/Referendum/Items/ReferendumItem/index.js
- src/components/Voting/Referendum/index.js
Actual changes in first commit, making eslint happy in second commit.
>  BLOCKCHAIN-304 - Remove endorse button + fix vote changing button 

- src/components/BackgroundBlocker/styles.module.scss
- src/components/Loader/NextBlockCountdown/index.js
- src/components/Loader/NextBlockCountdown/styles.module.scss
- src/components/Loader/index.js
- src/redux/reducers/blockchain.js
- src/redux/sagas/blockchain.js
- src/redux/selectors/blockchainSelectors.js
> BLOCKCHAIN-299 added block countdown to loader

- src/components/AuthComponents/SignIn/index.js
- src/components/AuthComponents/SignIn/styles.module.scss
> BLOCKCHAIN-289 FE Signup page cleanup

- package.json
- webpack.config.js
- yarn.lock
Update postcss-loader to 5.0.0 solve it
https://lightrun.com/answers/laravel-mix-laravel-mix-postcss-warning-that-it-does-nothing-no-plugin-is-set
> BLOCKCHAIN-311 change version of postcss-loader to 5.0.0

- src/assets/base/_variables.scss
- src/components/Button/styles.module.scss
- src/components/Home/HomeNavigation/styles.module.scss
- src/components/Proposal/index.js
- src/components/Proposal/styles.module.scss
- src/components/Tabs/styles.module.scss
- src/components/Voting/Referendum/Items/Details/index.js
- src/components/Voting/Referendum/Items/Discussions/index.js
- src/components/Voting/Referendum/Items/Header/index.js
- src/components/Voting/Referendum/Items/ProposalItem/index.js
- src/components/Voting/Referendum/Items/ProposalItem/styles.module.scss
- src/components/Voting/Referendum/Items/ReferendumItem/index.js
- src/components/Voting/Referendum/Items/ReferendumItem/styles.module.scss
- src/components/Voting/Referendum/Items/item.module.scss
- src/components/Voting/Referendum/Items/types.js
- src/components/Voting/Referendum/ProposalForms/AddLegislation/AddLegislation.js
- src/components/Voting/Referendum/index.js
- src/components/Voting/Referendum/styles.module.scss
- src/components/Voting/index.js
- src/components/Voting/styles.module.scss
CHECK AFTER BLOCKCHAIN-338, or compare it to BLOCKCHAIN-338!
> Blockchain 339 referenda

- src/api/explorer.js
- src/components/Wallet/WalletTransactionHistory/index.js
- src/components/Wallet/WalletTransactionHistory/styles.module.scss
draft until chain explorer pr deployed
https://github.com/liberland/chain_explorer/pull/15
> Blockchain 378 fe transaction history should show staking payouts

- package.json
- src/api/nodeRpcCall.js
- src/components/Contracts/Contract/index.js
- src/components/Contracts/ContractsList/index.js
- src/components/Contracts/CreateContract/index.js
- src/components/Contracts/CreateContract/styles.module.scss
- src/components/Contracts/Home/index.js
- src/components/Contracts/MyContracts/index.js
- src/redux/actions/contracts.js
- src/redux/reducers/contracts.js
- src/redux/sagas/contracts.js
- src/redux/sagas/index.js
- src/redux/selectors/contracts.js
- yarn.lock
Added create contract api call
> BLOCKCHAIN-412  FE Create contracts

- src/api/nodeRpcCall.js
- src/components/Modals/UnbondModal.js
- src/components/Staking/StakeManagement/Unbonding/index.js
- src/components/Staking/StakeManagement/WithdrawUnbondedButton/index.js
- src/components/Staking/StakeManagement/index.js
- src/redux/actions/validator.js
- src/redux/reducers/blockchain.js
- src/redux/reducers/validator.js
- src/redux/sagas/index.js
- src/redux/sagas/validator.js
- src/redux/selectors/validator.js
- src/utils/staking.js
> BLOCKCHAIN-413 FE unstaking bullshit numbers - Added detailed duration info

- src/api/nodeRpcCall.js
The issue happens when validator removes the stash completely by unbonding & withdrawing everything. I've recreated it locally and checked with Polkadot.js Apps and the same thing happens there - they show up as pending rewards, but can't be paid out:
On it's own it wouldn't be a big issue, but we're batching payouts for multiple validators, so it actually blocks user from paying our anything for 84 eras (as that's when the broken one will expire). Polkadot.js Apps does allow to do payouts only on specific validators, so they're not affected as much as we are.
Solution: just remove these broken validators from any calculations & payouts.
> Fix payouts when some validators are no longer stashes

- src/api/explorer.js
> BLOCKCHAIN-422 FE - Add HASHI SORA bridge transactions to transaction history

- src/api/middleware.js
- src/components/Offices/Finances/index.js
- src/components/Voting/CongressionalAssemble/CongressionalCountdown/index.js
- src/components/Voting/CongressionalAssemble/index.js
- src/redux/actions/finances.js
- src/redux/actions/index.js
- src/redux/reducers/finances.js
- src/redux/reducers/index.js
- src/redux/sagas/finances.js
- src/redux/sagas/index.js
- src/redux/selectors/finances.js
- src/redux/selectors/index.js
Add government financial metrics under the table of its wallets. Also fix a glitch in election countdown.
> Add government financial metrics

- src/api/ethereum.js
- src/components/Staking/ETHLPStaking/index.js
- src/components/Wallet/EthereumSelectorAddress/index.js
Simplify error message to prevent crashes
> BLOCKCHAIN-522 Hotfix provider failure

- src/components/Wallet/AssetOverview/index.js
Broken by https://github.com/liberland/liberland_frontend/pull/331/files#diff-7c6023221b0ee7c6ac5513f3626786e9b20f17f47141ca826e71567981723185
> Fix assets send button

- src/components/Loader/index.js
- src/components/Modals/AddLiquidityModal.js
- src/components/Modals/TradeTokens.js
- src/components/Modals/components/ModalWrapper.js
- src/components/Modals/styles.module.scss
- src/components/Wallet/Exchange/ExchangeItem/index.js
- src/context/modalContext/index.js
- src/redux/reducers/wallet.js
- src/redux/sagas/wallet.js
- src/utils/dexFormatter.js
This branch used modal refactor branch.
https://github.com/liberland/liberland_frontend/pull/377
> Blockchain 570 fe dex simpler design

- src/components/Staking/ETHLPStaking/index.js
- src/components/Staking/SOLLPStaking/index.js
Need to wait for docs update to go live first
> add sol staking instructions
